version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "mysql123456"
      MYSQL_ROOT_PASSWORD: "mysql123456"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - my-mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8085:15672"
      - "5672:5672"
    volumes:
      - my-rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret123
      - RABBITMQ_DEFAULT_USER=mqadmin
      - RABBITMQ_DEFAULT_PASS=Mqadmin

volumes:
  my-db:
  my-mongo:
  my-rabbitmq:
